name: Code Checking
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checking:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Test Build
        env:
          CI: ""
        run: |
          cd web
          REACT_APP_VERSION=$(git describe --tags) chmod u+x ./build.sh && ./build.sh --lint
          cd ..
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          install-mode: binary
          version: latest
          args: --timeout=10m

      - name: Test Build of Go
        run: go build
        
      - name: Check English Translation Coverage
        run: |
          python ./i18n/translate.py --repository_path . --json_file_path ./i18n/en.json
          python ./i18n/check-if-chn-exists.py .